export const calendarData = {
    Monday: [
        { code: "INTE 302", desc: "Information Assurance and Security 1", time: "10:30AM - 01:30PM", faculty: "MANDIGMA, J.", color: "bg-blue-100 border-blue-300 text-slate-900" },
        { code: "GEED 008", desc: "Ethics/Etika", time: "01:30PM - 04:30PM", faculty: "BOLAÑOS, K.", color: "bg-green-100 border-green-300 text-slate-900" },
        { code: "COMP 035", desc: "Data Mining", time: "04:30PM - 07:30PM", faculty: "BELARMINO, F.", color: "bg-purple-100 border-purple-300 text-slate-900" },
    ],
    Tuesday: [
        { code: "GEED 003", desc: "The Contemporary World", time: "10:30AM - 01:30PM", faculty: "DALUPANG, J.", color: "bg-yellow-100 border-yellow-300 text-slate-900" },
        { code: "COMP 019", desc: "Applications Development...", time: "03:00PM - 09:00PM", faculty: "ESPARRAGO, Y.", color: "bg-red-100 border-red-300 text-slate-900" },
    ],
    Wednesday: [],
    Thursday: [
        { code: "INTE 302", desc: "Information Assurance and Security 1", time: "10:30AM - 01:30PM", faculty: "MANDIGMA, J.", color: "bg-blue-100 border-blue-300 text-slate-900" },
        { code: "COMP 019", desc: "Applications Development...", time: "03:00PM - 09:00PM", faculty: "ESPARRAGO, Y.", color: "bg-red-100 border-red-300 text-slate-900" },
        { code: "COMP 035", desc: "Data Mining", time: "04:30PM - 07:30PM", faculty: "TBA", color: "bg-purple-100 border-purple-300 text-slate-900" },
    ],
    Friday: [
        { code: "HRMA 001", desc: "Principles of Organization...", time: "10:30AM - 01:30PM", faculty: "BRAGAS, L.", color: "bg-teal-100 border-teal-300 text-slate-900" },
        { code: "INTE 303", desc: "Capstone Project 1", time: "04:00PM - 09:00PM", faculty: "ESCUETA, N.", color: "bg-orange-100 border-orange-300 text-slate-900" },
    ]
};

export const Students = {
    officers: [
        {
            studImg: "",
            name: "Abot, Alessandra I.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                {
            studImg: "",
            name: "Aceitunas, Leo Miguel, B.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                {
            studImg: "",
            name: "Angeles, Allaine Jacob C.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                {
            studImg: "",
            name: "Aro, Rupert Matthew W.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                        {
            studImg: "",
            name: "Arriola, Ela Juris P.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                        {
            studImg: "",
            name: "Barbolino, Ianne Zhane T.",
            nickname: "nickname here",
            role: "CONTENT COMMITTEE",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                        {
            studImg: "",
            name: "Beltran, Aliah Joyce, M.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                        {
            studImg: "",
            name: "Calapatia, Raziela T.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                        {
            studImg: "",
            name: "Calata, Bianca N.",
            nickname: "nickname here",
            role: "SOCMED COMMITTEE",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                        {
            studImg: "",
            name: "Camorongan, Christine Lei R.",
            nickname: "nickname here",
            role: "HEAD OF SOCMED COMMITTEE",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                        {
            studImg: "",
            name: "Catampatan, Ayse M.",
            nickname: "nickname here",
            role: "SECRETARY",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                        {
            studImg: "",
            name: "Cayona, Chrisel Franzel C.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                        {
            studImg: "",
            name: "Damicog, Kyrsten Daphne M.",
            nickname: "nickname here",
            role: "CONTENT COMMITTEE",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                        {
            studImg: "lance.png",
            name: "Dayawon, Lance Joseph M.",
            nickname: "Nep",
            role: "PRESIDENT",
            subRole: "",
            quotes: "Driven by purpose, guided by faith.",
            hobby: "Music",
            color: "Black/White/Sky Blue",
            ig: "ig here",
            github: "https://github.com/lancejosephmdayawon/"
        },
                        {
            studImg: "divine.jpg",
            name: "Del Rosario, Divine Rose A.",
            nickname: "Vine",
            role: "STUDENT",
            subRole: "",
            quotes: "Food comes to those who loves to cook. ",
            hobby: "Cooking/Baking",
            color: "Pink",
            ig: "ig here",
            github: "github here"
        },
                        {
            studImg: "",
            name: "Dela Cruz, Luis Gabriel, F.",
            nickname: "nickname here",
            role: "PIO 2",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                        {
            studImg: "",
            name: "Dela Vega, Bianca A.",
            nickname: "nickname here",
            role: "SOCMED COMMITTEE",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                        {
            studImg: "",
            name: "Delda, Zellphie M.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                        {
            studImg: "",
            name: "Delos Reyes, Joshua L.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                        {
            studImg: "",
            name: "Diaz, Elexys Rae T.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                        {
            studImg: "",
            name: "Estalilla, Johanna Angela P.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                        {
            studImg: "",
            name: "Fababier, Jarell Vincent N.",
            nickname: "nickname here",
            role: "HEAD OF TECHNICAL COMMITTEE",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                        {
            studImg: "",
            name: "Fajardo, Bonna Mae T.",
            nickname: "nickname here",
            role: "TREASURER",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                        {
            studImg: "",
            name: "Felonia, Hannah Sophia N.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                        {
            studImg: "kelia.jpg",
            name: "Gamayo, Kelia Audrey S.",
            nickname: "Keliya",
            role: "PIO 1",
            subRole: "",
            quotes: "for love, to love, with love. ",
            hobby: "reading, music, and going to cafés",
            color: "Purple and Yellow",
            ig: "kasgamayo",
            github: "https://github.com/kasgamayo"
        },
                        {
            studImg: "",
            name: "Gran, Henry Louis S.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                        {
            studImg: "",
            name: "Gutierrez, John Evans L.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                        {
            studImg: "",
            name: "Harina, Sarah Mae D.C.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                        {
            studImg: "",
            name: "Ignacio, Lia Marielle E.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                        {
            studImg: "",
            name: "Imperial, Denzel Red D.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                               {
            studImg: "",
            name: "Jacolbia, Jan Marc S.",
            nickname: "nickname here",
            role: "CONTENT COMMITTEE",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                                       {
            studImg: "",
            name: "Jamot, Jonas J.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                                       {
            studImg: "",
            name: "Laranang, Sophia R.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                                       {
            studImg: "keith.png",
            name: "Lontoc, Keith Daryl A.",
            nickname: "Kit",
            role: "STUDENT",
            subRole: "",
            quotes: "It's not about how much time you have, it's how you use it.",
            hobby: "toy collecting",
            color: "purple",
            ig: "https://www.instagram.com/modelkitsnikit/",
            github: "https://github.com/KitKatCute"
        },
                                       {
            studImg: "",
            name: "Lopez, Angel Grace D.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                                       {
            studImg: "",
            name: "Lopez, Roman Aragorn T.",
            nickname: "nickname here",
            role: "CREATIVES COMMITTEE",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                                       {
            studImg: "",
            name: "Magpantay Reina D.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                                       {
            studImg: "",
            name: "Makiling, Mike Jerome P.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                                       {
            studImg: "",
            name: "Mamaril, Tricia Mae C.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                                       {
            studImg: "",
            name: "Mondragon, Ken John S.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                                       {
            studImg: "",
            name: "Pabayo, Glenn Carlo U.",
            nickname: "nickname here",
            role: "HEAD OF CONTENT COMMITTEE",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                                       {
            studImg: "",
            name: "Padrique, Ferlyn C.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                                       {
            studImg: "",
            name: "Ramirez, Francheska E.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                                       {
            studImg: "",
            name: "Ramos, Kyle Shannyn S.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                                       {
            studImg: "Reyes, Juan Miguel G.",
            name: "",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                                       {
            studImg: "",
            name: "Sebido, Mhaine M.",
            nickname: "Maen",
            role: "HEAD OF CREATIVES COMMITTEE",
            subRole: "",
            quotes: "quotes here",
            hobby: "watching anime",
            color: "purple, light pink",
            ig: "https://www.instagram.com/mmhne_/",
            github: "https://github.com/mhne-seb"
        },
                                       {
            studImg: "",
            name: "Segura, Odracir Rod Ivan T.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                                       {
            studImg: "",
            name: "Soriano, Micka Andrea M.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                                       {
            studImg: "",
            name: "Sy, Zachary M.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                                       {
            studImg: "",
            name: "Tanawan, Joshua C.",
            nickname: "nickname here",
            role: "CONTENT COMMITTEE ",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                                       {
            studImg: "",
            name: "Taroma, Yra Louisse M.",
            nickname: "nickname here",
            role: "VICE PRESIDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                                       {
            studImg: "",
            name: "Torres, Juan Miguel G.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                                       {
            studImg: "",
            name: "Urbano, Cyris Gale F.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                                       {
            studImg: "",
            name: "Velayo, Josef Karol A.",
            nickname: "nickname here",
            role: "CONTENT COMMITTEE",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                                       {
            studImg: "",
            name: "Villegas, Ian Christopher A.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
        
        
        
    ],
    class: [
  
    ],
};

export const Projects = [
    {
        picProj: "edurates.png",
        titleProj: "EduRate - Faculty Evaluation System",
        descProj: "A comprehensive faculty evaluation system designed to streamline the assessment of school educators through a secure and structured platform.",
        tools: ["PHP", "Laravel", "MySql"],
        developers: "Leo Miguel Aceitunas, Mhaine Sebido, Zellphie Delda, Raziela Calapatia, Yra Louisse Taroma" 
    },
    {
        picProj: "iskonnec.png",
        titleProj: "ISKOnnect - Student Social Networking System",
        descProj: "A dedicated social networking hub for students to connect, collaborate, and grow within a secure and supportive campus community.",
        tools: ["Laravel", "Tailwind", "MySql"],
        developers: "Allaine Jacob Angeles, Rupert Matthew  Aro, Kyrsten Daphne Damicog, Luis Gabriel Dela Cruz, Jan Marc  Jacolbia, Micka Andrea Soriano"
    },
    {
        picProj: "pupshelf.png",
        titleProj: "PUPSHELF - Library Management System",
        descProj: "Designed as an all-in-one digital hub, PUPSHELF is a library website that bridges the gap between administration and learning. It streamlines inventory management for our librarians and guarantees students effortless access to all library services with just a few clicks.",
        tools: ["Laravel", "PHP", "MySQL", "HTML", "CSS", "JavaScript"],
        developers: "Bianca Weizenthal, Jarell Vincent Fababier, Johanna Estalilla,Christine Lei Camorongan, Rei Magpantay, Zachary Sy"
    },
        {
        picProj: "iskorrection.png",
        titleProj: "Iskorrections - Student Violation System",
        descProj: "The system is a web-based platform designed to manage and monitor student violations in the university. It allows administrators to record violations and apply sanctions automatically, while students can view their records and submit appeals if needed.",
        tools: ["Blade", "PHP", "SCSS", "JavaScript"],
        developers: "Ayse Catampatan, Joshua Delos Reyes, Hannah Sophia Felonia, Roman Aragorn Lopez, Joshua Tanawan"
    },
];