export const calendarData = {
    Monday: [
        { code: "INTE 302", desc: "Information Assurance and Security 1", time: "10:30AM - 01:30PM", faculty: "MANDIGMA, J.", color: "bg-blue-100 border-blue-300 text-slate-900" },
        { code: "GEED 008", desc: "Ethics/Etika", time: "01:30PM - 04:30PM", faculty: "BOLAÑOS, K.", color: "bg-green-100 border-green-300 text-slate-900" },
        { code: "COMP 035", desc: "Data Mining", time: "04:30PM - 07:30PM", faculty: "BELARMINO, F.", color: "bg-purple-100 border-purple-300 text-slate-900" },
    ],
    Tuesday: [
        { code: "GEED 003", desc: "The Contemporary World", time: "10:30AM - 01:30PM", faculty: "DALUPANG, J.", color: "bg-yellow-100 border-yellow-300 text-slate-900" },
        { code: "COMP 019", desc: "Applications Development...", time: "03:00PM - 09:00PM", faculty: "ESPARRAGO, Y.", color: "bg-red-100 border-red-300 text-slate-900" },
    ],
    Wednesday: [],
    Thursday: [
        { code: "INTE 302", desc: "Information Assurance and Security 1", time: "10:30AM - 01:30PM", faculty: "MANDIGMA, J.", color: "bg-blue-100 border-blue-300 text-slate-900" },
        { code: "COMP 019", desc: "Applications Development...", time: "03:00PM - 09:00PM", faculty: "ESPARRAGO, Y.", color: "bg-red-100 border-red-300 text-slate-900" },
        { code: "COMP 035", desc: "Data Mining", time: "04:30PM - 07:30PM", faculty: "TBA", color: "bg-purple-100 border-purple-300 text-slate-900" },
    ],
    Friday: [
        { code: "HRMA 001", desc: "Principles of Organization...", time: "10:30AM - 01:30PM", faculty: "BRAGAS, L.", color: "bg-teal-100 border-teal-300 text-slate-900" },
        { code: "INTE 303", desc: "Capstone Project 1", time: "04:00PM - 09:00PM", faculty: "ESCUETA, N.", color: "bg-orange-100 border-orange-300 text-slate-900" },
    ]
};

export const Students = {
    officers: [
        {
            studImg: "",
            name: "Abot, Alessandra I.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                {
            studImg: "leo.jpg",
            name: "Aceitunas, Leo Miguel, B.",
            nickname: "Leo",
            role: "STUDENT",
            subRole: "",
            quotes: "“If you don’t take risks, you can’t create a future.”  - Monkey D. Luffy",
            hobby: "music",
            color: "red",
            ig: "lmiggy_",
            github: "lm-ace"
        },
                {
            studImg: "",
            name: "Angeles, Allaine Jacob C.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                {
            studImg: "",
            name: "Aro, Rupert Matthew W.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                        {
            studImg: "",
            name: "Arriola, Ela Juris P.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                        {
            studImg: "",
            name: "Barbolino, Ianne Zhane T.",
            nickname: "nickname here",
            role: "CONTENT COMMITTEE",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                        {
            studImg: "",
            name: "Beltran, Aliah Joyce, M.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                        {
            studImg: "",
            name: "Calapatia, Raziela T.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                        {
            studImg: "",
            name: "Calata, Bianca N.",
            nickname: "nickname here",
            role: "SOCMED COMMITTEE",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                        {
            studImg: "lei.png",
            name: "Camorongan, Christine Lei R.",
            nickname: "Lei",
            role: "HEAD OF SOCMED COMMITTEE",
            subRole: "",
            quotes: "Own Lane, Own Wave, Own Pace",
            hobby: "reading & playing Games",
            color: "purple",
            ig: "z_iellll",
            github: "LeiCamorongan"
        },
                        {
            studImg: "ayse.jpeg",
            name: "Catampatan, Ayse M.",
            nickname: "Seeyah",
            role: "SECRETARY",
            subRole: "",
            quotes: "living for the thrill",
            hobby: "gaming",
            color: "maroon",
            ig: "yy_yesha",
            github: "seeyahhh"
        },
                        {
            studImg: "",
            name: "Cayona, Chrisel Franzel C.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                        {
            studImg: "kyrsten.jpeg",
            name: "Damicog, Kyrsten Daphne M.",
            nickname: "daphne",
            role: "CONTENT COMMITTEE",
            subRole: "",
            quotes: "Last Hope - Paramore || [00:38-00:46]",
            hobby: "music",
            color: "violet",
            ig: "kyrstnxx",
            github: "github here"
        },
                        {
            studImg: "lance.png",
            name: "Dayawon, Lance Joseph M.",
            nickname: "Nep",
            role: "PRESIDENT",
            subRole: "",
            quotes: "Driven by purpose, guided by faith.",
            hobby: "Music",
            color: "Black/White/Sky Blue",
            ig: "ig here",
            github: "https://github.com/lancejosephmdayawon/"
        },
                        {
            studImg: "divine.jpg",
            name: "Del Rosario, Divine Rose A.",
            nickname: "Vine",
            role: "STUDENT",
            subRole: "",
            quotes: "Food comes to those who loves to cook. ",
            hobby: "Cooking/Baking",
            color: "Pink",
            ig: "ig here",
            github: "github here"
        },
                        {
            studImg: "luis.jpeg",
            name: "Dela Cruz, Luis Gabriel, F.",
            nickname: "wizZ",
            role: "PIO 2",
            subRole: "",
            quotes: "yes gawd — okurrrrrrrr */deathdrop",
            hobby: "watching reality shows, Cooking, playing games",
            color: "yellow, blue, violet, pink, green",
            ig: "gagagagagabo",
            github: "lui-sss"
        },
                        {
            studImg: "",
            name: "Dela Vega, Bianca A.",
            nickname: "nickname here",
            role: "SOCMED COMMITTEE",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                        {
            studImg: "",
            name: "Delda, Zellphie M.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                        {
            studImg: "",
            name: "Delos Reyes, Joshua L.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                        {
            studImg: "",
            name: "Diaz, Elexys Rae T.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                        {
            studImg: "",
            name: "Estalilla, Johanna Angela P.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                        {
            studImg: "",
            name: "Fababier, Jarell Vincent N.",
            nickname: "nickname here",
            role: "HEAD OF TECHNICAL COMMITTEE",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                        {
            studImg: "",
            name: "Fajardo, Bonna Mae T.",
            nickname: "nickname here",
            role: "TREASURER",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                        {
            studImg: "hannah.jpg",
            name: "Felonia, Hannah Sophia N.",
            nickname: "hannah",
            role: "STUDENT",
            subRole: "",
            quotes: "Still blooming through the seasons of life ",
            hobby: "gaming & sleeping 😴",
            color: "yellow & pink",
            ig: "hnhxsphia_",
            github: "sophiahannah"
        },
                        {
            studImg: "kelia.jpg",
            name: "Gamayo, Kelia Audrey S.",
            nickname: "Keliya",
            role: "PIO 1",
            subRole: "",
            quotes: "for love, to love, with love. ",
            hobby: "reading, music, going to cafés",
            color: "Purple and Yellow",
            ig: "kasgamayo",
            github: "https://github.com/kasgamayo"
        },
                        {
            studImg: "",
            name: "Gran, Henry Louis S.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                        {
            studImg: "evans.jpeg",
            name: "Gutierrez, John Evans L.",
            nickname: "Vans",
            role: "STUDENT",
            subRole: "",
            quotes: "This is my peak",
            hobby: "chess and drawing",
            color: "crimson red",
            ig: "ig here",
            github: "Sucro-Law"
        },
                        {
            studImg: "",
            name: "Harina, Sarah Mae D.C.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                        {
            studImg: "lia.jpeg",
            name: "Ignacio, Lia Marielle E.",
            nickname: "Lia",
            role: "STUDENT",
            subRole: "",
            quotes: "Mind over matter.",
            hobby: "reading books",
            color: "red",
            ig: "lmrielle_",
            github: "lmrielle"
        },
                        {
            studImg: "denzel.png",
            name: "Imperial, Denzel Red D.",
            nickname: "Denz",
            role: "Creatives Committee",
            subRole: "",
            quotes: "party!",
            hobby: "Playing Valorant, MLBB",
            color: "Pink / Red",
            ig: "d_r3di",
            github: "Denz14-RDI"
        },
                               {
            studImg: "",
            name: "Jacolbia, Jan Marc S.",
            nickname: "nickname here",
            role: "CONTENT COMMITTEE",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                                       {
            studImg: "",
            name: "Jamot, Jonas J.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                                       {
            studImg: "",
            name: "Laranang, Sophia R.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                                       {
            studImg: "keith.png",
            name: "Lontoc, Keith Daryl A.",
            nickname: "Kit",
            role: "STUDENT",
            subRole: "",
            quotes: "It's not about how much time you have, it's how you use it.",
            hobby: "toy collecting",
            color: "purple",
            ig: "https://www.instagram.com/modelkitsnikit/",
            github: "https://github.com/KitKatCute"
        },
                                       {
            studImg: "",
            name: "Lopez, Angel Grace D.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                                       {
            studImg: "",
            name: "Lopez, Roman Aragorn T.",
            nickname: "nickname here",
            role: "CREATIVES COMMITTEE",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                                       {
            studImg: "",
            name: "Magpantay Reina D.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                                       {
            studImg: "",
            name: "Makiling, Mike Jerome P.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                                       {
            studImg: "tricia.jpg",
            name: "Mamaril, Tricia Mae C.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "Live as if you were to die tomorrow",
            hobby: "gaming",
            color: "violet",
            ig: "ig here",
            github: "github here"
        },
                                       {
            studImg: "",
            name: "Mondragon, Ken John S.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                                       {
            studImg: "",
            name: "Pabayo, Glenn Carlo U.",
            nickname: "nickname here",
            role: "HEAD OF CONTENT COMMITTEE",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                                       {
            studImg: "",
            name: "Padrique, Ferlyn C.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                                       {
            studImg: "",
            name: "Ramirez, Francheska E.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                                       {
            studImg: "",
            name: "Ramos, Kyle Shannyn S.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                                       {
            studImg: "",
            name: "Reyes, Juan Miguel G.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                                       {
            studImg: "maen.png",
            name: "Sebido, Mhaine M.",
            nickname: "Maen",
            role: "HEAD OF CREATIVES COMMITTEE",
            subRole: "",
            quotes: "go and try, reach the sky.✨",
            hobby: "watching anime",
            color: "purple, light pink",
            ig: "https://www.instagram.com/mmhne_/",
            github: "https://github.com/mhne-seb"
        },
                                       {
            studImg: "ivan.png",
            name: "Segura, Odracir Rod Ivan T.",
            nickname: "Ivan / Van",
            role: "STUDENT",
            subRole: "",
            quotes: "After all this time? Always.",
            hobby: "reading, eating, playing",
            color: "Blue (Sky blue)",
            ig: "_ivnwho",
            github: "github here"
        },
                                       {
            studImg: "",
            name: "Soriano, Micka Andrea M.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                                       {
            studImg: "",
            name: "Sy, Zachary M.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                                       {
            studImg: "joshua.jpeg",
            name: "Tanawan, Joshua C.",
            nickname: "Tosh",
            role: "CONTENT COMMITTEE ",
            subRole: "",
            quotes: "To create something worthwhile",
            hobby: "content creation",
            color: "green",
            ig: "tanawan_josh",
            github: "github here"
        },
                                       {
            studImg: "",
            name: "Taroma, Yra Louisse M.",
            nickname: "nickname here",
            role: "VICE PRESIDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                                       {
            studImg: "jm.png",
            name: "Torres, Juan Miguel G.",
            nickname: "JM",
            role: "STUDENT",
            subRole: "",
            quotes: "🤖☝🏼",
            hobby: "gaming, music, sports",
            color: "Sunset Orange",
            ig: "the.jeyemz",
            github: "github here"
        },
                                       {
            studImg: "",
            name: "Urbano, Cyris Gale F.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                                       {
            studImg: "",
            name: "Velayo, Josef Karol A.",
            nickname: "nickname here",
            role: "CONTENT COMMITTEE",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
                                       {
            studImg: "",
            name: "Villegas, Ian Christopher A.",
            nickname: "nickname here",
            role: "STUDENT",
            subRole: "",
            quotes: "quotes here",
            hobby: "hobby here",
            color: "fav color here",
            ig: "ig here",
            github: "github here"
        },
        
        
        
    ],
    class: [
  
    ],
};

export const Projects = [
    {
        picProj: "edurates.png",
        titleProj: "EduRate - Faculty Evaluation System",
        descProj: "A comprehensive faculty evaluation system designed to streamline the assessment of school educators through a secure and structured platform.",
        tools: ["PHP", "Laravel", "MySql"],
        developers: "Leo Miguel Aceitunas, Mhaine Sebido, Zellphie Delda, Raziela Calapatia, Yra Louisse Taroma" 
    },
    {
        picProj: "iskonnec.png",
        titleProj: "ISKOnnect - Student Social Networking System",
        descProj: "A dedicated social networking hub for students to connect, collaborate, and grow within a secure and supportive campus community.",
        tools: ["Laravel", "Tailwind", "MySql"],
        developers: "Allaine Jacob Angeles, Rupert Matthew  Aro, Kyrsten Daphne Damicog, Luis Gabriel Dela Cruz, Jan Marc  Jacolbia, Micka Andrea Soriano"
    },
    {
        picProj: "pupshelf.png",
        titleProj: "PUPSHELF - Library Management System",
        descProj: "Designed as an all-in-one digital hub, PUPSHELF is a library website that bridges the gap between administration and learning. It streamlines inventory management for our librarians and guarantees students effortless access to all library services with just a few clicks.",
        tools: ["Laravel", "PHP", "MySQL", "HTML", "CSS", "JavaScript"],
        developers: "Bianca Weizenthal, Jarell Vincent Fababier, Johanna Estalilla,Christine Lei Camorongan, Rei Magpantay, Zachary Sy"
    },
        {
        picProj: "iskorrection.png",
        titleProj: "Iskorrections - Student Violation System",
        descProj: "The system is a web-based platform designed to manage and monitor student violations in the university. It allows administrators to record violations and apply sanctions automatically, while students can view their records and submit appeals if needed.",
        tools: ["Blade", "PHP", "SCSS", "JavaScript"],
        developers: "Ayse Catampatan, Joshua Delos Reyes, Hannah Sophia Felonia, Roman Aragorn Lopez, Joshua Tanawan"
    },
        {
        picProj: "iskolib.png",
        titleProj: "Iskolib - Library Management System",
        descProj: "ISKO-LIB is a web-based library management system that streamlines book, category, and inventory management for academic institutions through a centralized, user-friendly interface.",
        tools: ["Laravel", "PHP", "Blade", "MySQL", "Figma"],
        developers: "Lance Joseph Dayawon, Glenn Carlo Pabayo, Ian Villegas, Odracir Segura, Sarah Mae Harina, Tricia Mamaril"
    },
            {
        picProj: "edvaluate.jfif",
        titleProj: "EdValuate: School Faculty Performance Evaluation System",
        descProj: "EdValuate is a secure platform that facilitates students to anonymously rate and provide feedback on faculty teaching performance, supporting academic development within the institution.",
        tools: ["PHP", "JavaScript", "HTML", "CSS", "Laravel"],
        developers: "Alessandra Abot, Aliah Joyce Beltran, Bianca Isabelle Dela Vega, Henry Louis Gran, Angel Grace Lopez"
    },
                {
        picProj: "pupcom.png",
        titleProj: "PUPCOM - Student Networking System",
        descProj: "PUPCOM is a student-centered social networking platform designed exclusively for the PUP community.",
        tools: ["HTML", "CSS", "JavaScript", "PHP", "MySQL", "Figma"],
        developers: "Imperial Denzel Red D., Reyes Juan Miguel G., Arriola Ela Juris P., Fajardo Bonna Mae T., Jamot Jonas J., Ignacio Lia Marielle E."
    },
];